owner: juan294
repo: paisaxe-upptime

sites:
  - name: Paisaxe (Main Site)
    url: https://paisaxe.com
    method: GET
    expectedStatusCode: 200

  - name: Paisaxe API Health
    url: https://paisaxe.com/api/health
    method: GET
    expectedStatusCode: 200

status-website:
  baseUrl: /paisaxe-upptime
  logoUrl: https://raw.githubusercontent.com/juan294/paisaxe-upptime/master/.github/logo.svg
  name: Paisaxe Status
  introTitle: "**Paisaxe** status and uptime monitoring."
  introMessage: This status page tracks the availability of [Paisaxe](https://paisaxe.com), an immersive tourism experience for Asturias, Spain.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
